# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-13 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortnerurl',
            name='shortcode',
            field=models.CharField(default='defaultsc', max_length=15),
            preserve_default=False,
        ),
    ]
