# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-13 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0002_shortnerurl_shortcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortnerurl',
            name='shortcode',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
