# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-13 18:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0003_auto_20170713_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortnerurl',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 7, 13, 18, 18, 36, 82784)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shortnerurl',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
