# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-13 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0004_auto_20170713_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortnerurl',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='shortnerurl',
            name='shortcode',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
