# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-20 08:31
from __future__ import unicode_literals

from django.db import migrations, models
import shortner.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0005_auto_20170713_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortnerurl',
            name='url',
            field=models.CharField(max_length=220, validators=[shortner.validators.validate_url, shortner.validators.validate_dot_com]),
        ),
    ]
